schema_version: 1

context:
  name: semantikon
  version: "1.4.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 30db96cae9d61e72b0331a2cc4e85b4bd7cecb54c3b1c44a46bea292a3240b03

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
  run:
    - bagofholding >=0.1.5,<0.2.0
    - flowrep >=0.6.0,<0.7.0
    - python >=${{ python_min }},<3.15
    - python-graphviz >=0.20.3,<=0.21
    - networkx >=3.5,<3.7.0
    - numpy >=1.26.4,<2.6.0
    - owlrl >=7.1.2,<7.7.0
    - pint >=0.24,<=0.25.3
    - rdflib >=7.1.1,<7.7.0
    - pyshacl >=0.30.0,<=0.40.1
    - requests >=2.28.0,<2.35.0
    - typeguard >=4.0.0,<4.6.0
tests:
  - python:
      imports:
        - semantikon
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: semantikon - Ontological type system
  description: |
    In the realm of the workflow management systems, there are well defined inputs and outputs for each node. semantikon is a Python package to give scientific context to node inputs and outputs by providing type hinting and interpreters.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/semantikon
  repository: https://github.com/pyiron/semantikon
  documentation: https://semantikon.readthedocs.io/

extra:
  recipe-maintainers:
    - jan-janssen
    - samwaseda
    - liamhuber
